services:
  app:
    build: .
    ports:
      - "8080:8080"
    x-develop:
      watch:
        - action: sync
          path: ./static
          target: ./static
        - action: rebuild
          path: ./cmd
        - action: rebuild
          path: ./internal
        - action: rebuild
          path: Dockerfile